#!/usr/bin/env node
/**
 * Vercel build step — inject Render API URL into frontend/js/env.js
 * Set DARINFORMAL_API_URL in Vercel project environment variables.
 */
import { mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const apiUrl = process.env.DARINFORMAL_API_URL || 'https://darinformal-api.onrender.com/api';

if (!apiUrl.startsWith('http')) {
  console.error('DARINFORMAL_API_URL must be a full URL, e.g. https://your-api.onrender.com/api');
  process.exit(1);
}

const content = `// Auto-generated by Vercel build — do not edit
window.DARINFORMAL_API_URL = '${apiUrl.replace(/'/g, "\\'")}';
`;

const outPath = join(__dirname, '..', 'js', 'env.js');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, content, 'utf8');
console.log('Wrote env.js with API URL:', apiUrl);
