#!/usr/bin/env node
/**
 * Vercel build: writes js/env.js with your Render API URL.
 * Set in Vercel → Settings → Environment Variables:
 *   DARINFORMAL_API_URL = https://YOUR-SERVICE.onrender.com/api
 */
import { mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const apiUrl = (process.env.DARINFORMAL_API_URL || '').trim();

if (!apiUrl) {
  console.warn('WARNING: DARINFORMAL_API_URL not set — map will not load on Vercel until you add it.');
}

const safeUrl = (apiUrl || 'https://darinformal-api.onrender.com/api').replace(/'/g, "\\'");

const content = `// Auto-generated by Vercel build — do not edit manually
window.DARINFORMAL_API_URL = '${safeUrl}';
`;

const out = join(__dirname, '..', 'js', 'env.js');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, content, 'utf8');
console.log('API URL for frontend:', safeUrl);
