#!/usr/bin/env node
/**
 * Vercel build step — inject Render API URL into frontend/js/env.js
 * Set DARINFORMAL_API_URL in Vercel project environment variables.
 */
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const apiUrl = process.env.DARINFORMAL_API_URL || 'https://darinformal-api.onrender.com/api';

const content = `// Auto-generated by Vercel build — do not edit
window.DARINFORMAL_API_URL = '${apiUrl.replace(/'/g, "\\'")}';
window.DARINFORMAL_DEFAULT_RENDER_MODE = 'geojson';
`;

const outPath = join(__dirname, '..', 'js', 'env.js');
writeFileSync(outPath, content, 'utf8');
console.log('Wrote env.js with API URL:', apiUrl);
